{"timestamp": "2025-08-29T08:07:58.848706Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.api", "message": "\ud83d\udea8 PORTFOLIO LIMITED: Ledger router failed - portfolio will use demo data", "location": {"file": "D:\\dex\\backend\\app\\api\\__init__.py", "line": 167, "function": "<module>"}}
{"timestamp": "2025-08-29T08:08:03.147518Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:08:03.148577Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.core.lifespan", "message": "Failed to initialize Redis rate limiter", "location": {"file": "D:\\dex\\backend\\app\\core\\lifespan.py", "line": 111, "function": "setup_enhanced_rate_limiting"}}
{"timestamp": "2025-08-29T08:08:59.363219Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:09:33.400379Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:09:33.424364Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:09:59.335916Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:10:59.353225Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:11:59.353178Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:12:59.388699Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:13:59.408951Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:14:59.373284Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:15:59.427466Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:16:52.462884Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:16:52.463392Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:16:52.464448Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:16:56.581705Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:16:56.582760Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:16:56.582760Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:16:56.583767Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:16:57.813088Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:16:57.817973Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.api.wallet", "message": "Logging failed: \"Attempt to overwrite 'message' in LogRecord\". Original message: Wallet registration request received", "location": {"file": "D:\\dex\\backend\\app\\api\\wallet.py", "line": 198, "function": "log_wallet_operation"}}
{"timestamp": "2025-08-29T08:16:57.817973Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.api.wallet", "message": "Logging failed: \"Attempt to overwrite 'message' in LogRecord\". Original message: Wallet registration completed successfully", "location": {"file": "D:\\dex\\backend\\app\\api\\wallet.py", "line": 198, "function": "log_wallet_operation"}}
{"timestamp": "2025-08-29T08:16:57.932927Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.api.wallet", "message": "Logging failed: \"Attempt to overwrite 'message' in LogRecord\". Original message: Wallet registration metrics logged", "location": {"file": "D:\\dex\\backend\\app\\api\\wallet.py", "line": 198, "function": "log_wallet_operation"}}
{"timestamp": "2025-08-29T08:16:59.387028Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:00.639711Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:00.640798Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:01.467545Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:02.439796Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:04.711747Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:04.714455Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:04.724442Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:05.141376Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:06.489078Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:08.792694Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:08.793744Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:08.812246Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:10.577882Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:12.869581Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:12.873025Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:12.875562Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:14.648164Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:16.991498Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:16.992545Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:16.992545Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:18.699779Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:21.065334Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:21.067693Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:21.069909Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:22.778276Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:25.121670Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:25.126148Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:25.152187Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:26.853432Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:29.227561Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:29.228634Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:29.229139Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:30.951562Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:33.295254Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:33.315159Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:33.455603Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:35.028152Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:36.681668Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:36.683958Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:36.686081Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:36.686081Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:37.366013Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:37.381776Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:37.410801Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:39.089918Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:41.433855Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:41.434871Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:41.461005Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:43.148543Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:45.507312Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:45.508400Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:45.519429Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:47.193121Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:49.587831Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:49.588909Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:49.588909Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:51.254497Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:53.654748Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:53.681554Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:53.682239Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:55.341054Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:57.714832Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:57.752999Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:17:57.753897Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:01.782010Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:01.797809Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:01.825546Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:05.837916Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:05.851717Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:05.852740Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:09.911374Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:09.911374Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:09.950905Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:13.976526Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:13.977469Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:14.009707Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:18.033783Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:18.057921Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:18.059013Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:22.103955Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:22.119538Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:22.135229Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:26.156528Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:26.176987Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:26.177912Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:30.200726Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:30.255637Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:30.256681Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:34.247420Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:34.328461Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:34.331964Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:38.300384Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:38.388847Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
{"timestamp": "2025-08-29T08:18:38.427904Z", "level": "ERROR", "trace_id": "b99916fa-aeb2-4801-8908-1e5b813e5fdb", "module": "app.middleware.rate_limiting", "message": "Redis connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.", "location": {"file": "D:\\dex\\backend\\app\\middleware\\rate_limiting.py", "line": 303, "function": "connect"}}
